### ISSUE TITLE
It appears users don't have any way to deconstruct Clif

### ISSUE THREAD

**Issue by kitoran** [maaleske/clif#2]
I want to use this library, but i don't see how to get coordinates/components/coefficients associated with some blade back from Clif without importing Clif.Internal.

**Comment by maaleske** [comment]
That is an oversight, I've only used the library so far for checking pen & paper calculations so I didn't have a need for any actually useful features. I can probably add and export a `toList` function for Clifs.

**Comment by maaleske** [comment]
29d42d5a5cd7b2f8d9dfa72d945dd088ce4c9c5f adds a 'toList' for Clifs. Note that 'toList' and 'fromList' are not full inverses in the current implementation, since there's an issue with non-unique zero representations (which I'll have to fix at some point, but it'll probably need a bigger rework of the internals).
